# Generated by Django 3.2.5 on 2021-07-24 22:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighbourapp', '0004_newpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewPost',
            new_name='Announce',
        ),
    ]
