# Generated by Django 3.2.5 on 2021-07-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourapp', '0006_auto_20210725_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='woman.png', upload_to='images/'),
        ),
    ]
