# Generated by Django 3.2.5 on 2021-07-25 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourapp', '0009_auto_20210725_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='login',
            new_name='location',
        ),
    ]
